namespace Magizine.Shared.Enums;

/// <summary>
/// Valid values for <c>Tbl_Article.Status</c> (<c>varchar(20) NOT NULL DEFAULT 'Draft'</c>).
/// </summary>
/// <remarks>
/// The MEMBER NAME IS THE STORED VALUE - there is no mapping layer, so renaming a member is a
/// breaking data change. Stored as text (not an int) because the column is <c>varchar</c> and
/// the database is the source of truth; see <c>Doc\Rescaffold.ps1</c>.
///
/// The EF entity exposes this column as <c>string</c> rather than this enum on purpose:
/// <c>EFContext\TblArticle.cs</c> is regenerated by <c>dotnet ef dbcontext scaffold --force</c>
/// and any hand edit would be silently reverted. Use <see cref="EnumExtensions.ToEnum{TEnum}"/>
/// and <see cref="EnumExtensions.ToDbString{TEnum}"/> to cross that boundary explicitly.
/// </remarks>
public enum EnumArticleStatus
{
    /// <summary>Being written. Not visible to readers. Database default.</summary>
    Draft,

    /// <summary>Submitted for editorial review.</summary>
    InReview,

    /// <summary>Live and publicly visible. <c>PublishedAt</c> should be set alongside this.</summary>
    Published,

    /// <summary>Was published, now withdrawn from the public site. Retained for the record.</summary>
    Archived
}
