-- Supabase / PostgreSQL Schema for L'ÉDITION
-- Translates SQL Server types (NVARCHAR, BIT, DATETIME) to Postgres (VARCHAR, BOOLEAN, TIMESTAMPTZ)
-- IMPORTANT: Tables are created in dependency order (tables without Foreign Keys first).

-- 1. Tbl_Admin
CREATE TABLE "Tbl_Admin" (
    "AdminId" bigint generated by default as identity PRIMARY KEY,
    "Username" varchar(50) NOT NULL UNIQUE,
    "Email" varchar(100) NOT NULL UNIQUE,
    "PasswordHash" varchar(255) NOT NULL,
    "Role" varchar(30) NOT NULL DEFAULT 'Editor',
    "LastLoginAt" timestamptz NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 2. Tbl_Author
CREATE TABLE "Tbl_Author" (
    "AuthorId" bigint generated by default as identity PRIMARY KEY,
    "FirstName" varchar(50) NOT NULL,
    "LastName" varchar(50) NOT NULL,
    "Email" varchar(100) NOT NULL UNIQUE,
    "PasswordHash" varchar(255) NOT NULL,
    "Title" varchar(100) NULL,
    "Bio" varchar(500) NULL,
    "PhotoUrl" varchar(300) NULL,
    "InstagramUrl" varchar(300) NULL,
    "TwitterUrl" varchar(300) NULL,
    "WebsiteUrl" varchar(300) NULL,
    "Slug" varchar(100) NOT NULL UNIQUE,
    "IsApproved" boolean NOT NULL DEFAULT false,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 3. Tbl_ArticleCategory
CREATE TABLE "Tbl_ArticleCategory" (
    "ArticleCategoryId" bigint generated by default as identity PRIMARY KEY,
    "Name" varchar(20) NOT NULL UNIQUE,
    "Slug" varchar(30) NOT NULL UNIQUE,
    "Description" varchar(200) NULL,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 4. Tbl_Article
CREATE TABLE "Tbl_Article" (
    "ArticleId" bigint generated by default as identity PRIMARY KEY,
    "Title" varchar(200) NOT NULL,
    "SubTitle" varchar(400) NULL,
    "Slug" varchar(200) NOT NULL UNIQUE,
    "Body" text NULL,
    "PhotoUrl" varchar(300) NULL,
    "PhotoCaption" varchar(200) NULL,
    "PhotoCredit" varchar(100) NULL,
    "ArticleCategoryId" bigint NOT NULL REFERENCES "Tbl_ArticleCategory"("ArticleCategoryId"),
    "AuthorId" bigint NOT NULL REFERENCES "Tbl_Author"("AuthorId"),
    "Status" varchar(20) NOT NULL DEFAULT 'Draft',
    "PublishedAt" timestamptz NULL,
    "IsFeatured" boolean NOT NULL DEFAULT false,
    "IsSpotlight" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 5. Tbl_RequestArticle
CREATE TABLE "Tbl_RequestArticle" (
    "RequestArticleId" bigint generated by default as identity PRIMARY KEY,
    "PitcherName" varchar(100) NOT NULL,
    "PitcherEmail" varchar(100) NOT NULL,
    "ProposedTitle" varchar(200) NULL,
    "PitchBody" text NOT NULL,
    "ArticleCategoryId" bigint NULL REFERENCES "Tbl_ArticleCategory"("ArticleCategoryId"),
    "Status" varchar(20) NOT NULL DEFAULT 'Pending',
    "SubmittedAt" timestamptz NOT NULL DEFAULT now(),
    "ReviewedAt" timestamptz NULL,
    "ReviewedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId"),
    "AdminNotes" varchar(500) NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 6. Tbl_ContactMessage
CREATE TABLE "Tbl_ContactMessage" (
    "ContactMessageId" bigint generated by default as identity PRIMARY KEY,
    "SenderName" varchar(100) NOT NULL,
    "SenderEmail" varchar(100) NOT NULL,
    "Subject" varchar(200) NULL,
    "MessageBody" text NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT false,
    "ReadAt" timestamptz NULL,
    "ReadByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId"),
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 7. Tbl_Newsletter
CREATE TABLE "Tbl_Newsletter" (
    "NewsletterId" bigint generated by default as identity PRIMARY KEY,
    "Email" varchar(100) NOT NULL UNIQUE,
    "FullName" varchar(100) NULL,
    "SubscribedAt" timestamptz NOT NULL DEFAULT now(),
    "IsActive" boolean NOT NULL DEFAULT true,
    "UnsubscribedAt" timestamptz NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 8. Tbl_AboutAndAppData (NO Soft Delete columns per our decision)
CREATE TABLE "Tbl_AboutAndAppData" (
    "AppDataId" bigint generated by default as identity PRIMARY KEY,
    "Key" varchar(100) NOT NULL UNIQUE,
    "Value" text NULL,
    "GroupName" varchar(50) NULL,
    "UpdatedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId"),
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL
);

-- 9. Tbl_Notification
CREATE TABLE "Tbl_Notification" (
    "NotificationId" bigint generated by default as identity PRIMARY KEY,
    "RecipientAuthorId" bigint NULL REFERENCES "Tbl_Author"("AuthorId"),
    "RecipientAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId"),
    "Title" varchar(150) NOT NULL,
    "Message" varchar(500) NOT NULL,
    "Type" varchar(30) NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT false,
    "ReadAt" timestamptz NULL,
    "RelatedEntityType" varchar(50) NULL,
    "RelatedEntityId" bigint NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);

-- 10. Tbl_Ads
CREATE TABLE "Tbl_Ads" (
    "AdId" bigint generated by default as identity PRIMARY KEY,
    "Title" varchar(150) NOT NULL,
    "ImageUrl" varchar(300) NOT NULL,
    "TargetUrl" varchar(300) NULL,
    "Placement" varchar(50) NOT NULL,
    "ArticleCategoryId" bigint NULL REFERENCES "Tbl_ArticleCategory"("ArticleCategoryId"),
    "StartDate" timestamptz NULL,
    "EndDate" timestamptz NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "ClickCount" integer NOT NULL DEFAULT 0,
    "ImpressionCount" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamptz NULL,
    "DeletedByAdminId" bigint NULL REFERENCES "Tbl_Admin"("AdminId")
);
